Repository BHoM/ETABS_Toolkit, pull requests merged in 2019-11, with the labels that each got.

#223 Aligning with changes in BHoMAdapter
  Etabs_Adapter/Create/_Create.cs
  Etabs_Adapter/ETABSAdapter.cs
Labels: type:external-api-changes

#225 Update AssemblyVersion and AssemblyFileVersion to 3.0.0.0
  ETABS_Engine/Properties/AssemblyInfo.cs
  ETABS_oM/Properties/AssemblyInfo.cs
  Etabs_Adapter/Properties/AssemblyInfo.cs
Labels: type:compliance

#228 Update names of MeshResult classes
  Etabs_Adapter/Read/Result.cs
Labels: type:external-api-changes

#210 RigidLinks does not push
  Etabs_Adapter/Create/Link.cs
Labels: size:XS, type:bug
