Repository BHoM/ETABS_Toolkit, pull requests merged in 2019-12, with the labels that each got.

#231 Error-handling when pushing sections
  Etabs_Adapter/Create/Bar.cs
Labels: size:XS, type:bug

#234 MassSource Push Fix
  Etabs_Adapter/Create/Load.cs
Labels: type:bug

#235 Unnamed Levels Fix
  Etabs_Adapter/Create/Level.cs
Labels: type:bug

#236 Read Orientation angle for Bars
  Etabs_Adapter/Read/Bar.cs
Labels: type:bug

#238 BarVaryingDistributedLoad Extent Fix
  Etabs_Adapter/Create/Load.cs
Labels: type:bug

#241 Fixing material density pushed with wrong "option"
  Etabs_Adapter/Create/Material.cs
Labels: severity:critical, type:bug
